apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: openai-ui
  name: openai-ui
  namespace: openai-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openai-ui
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        io.kompose.service: openai-ui
    spec:
      containers:
        - image: ghcr.io/fhswf/openai-ui:0.12.11
          name: ui
          ports:
            - containerPort: 80
          env:
            - name: VITE_RELEASE
              value: 0.12.11
            - name: VITE_BUILD_SHA
              value: e97909b32fb5345ca17ea5c145750f3be8c3745c
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
            requests:
              memory: 64Mi
              cpu: 250m
      restartPolicy: Always
status: {}
