name: build

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set default (old) release version
        run: echo "RELEASE_VERSION=${{ steps.semantic_release.outputs.last_RELEASE_VERSION }}" >> $GITHUB_ENV  
      - name: Output release version
        run: echo "RELEASE_VERSION=${{ steps.semantic_release.outputs.new_RELEASE_VERSION }}" >> $GITHUB_ENV 
        if: steps.semantic_release.outputs.new_release_published == 'true'
      - name: Output release version
        run: echo "RELEASE_VERSION=${{ env.RELEASE_VERSION }}" 
    outputs:
      new_release_published: ${{ steps.semantic_release.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic_release.outputs.new_release_version }}
      last_release_version: ${{ steps.semantic_release.outputs.last_release_version }}
      release_version: ${{ env.RELEASE_VERSION }}
      
  build:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Output release version
        run: echo $RELEASE_VERSION

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/fhswf/openai-ui:latest, ghcr.io/fhswf/openai-ui:${{ github.sha }}, ghcr.io/fhswf/openai-ui:${{ env.RELEASE_VERSION }}
      
